# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Eternal Thinker
tagline:          Online workspace of Rahul Anand
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Rahul Anand
  url:            http://eternal-thinker.com/
  email:          et@eternal-thinker.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/eternalthinker
